import gql from 'graphql-tag'
import ProductFragment from './ProductFragment.gql'

const productsQuery = gql`
  query getProduct($productId: String!) {
    product(id: $productId) {
      ...ProductFragment
    }
  }
  ${ProductFragment}
`

export default productsQuery
